### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'uat'

### ISSUE THREAD

**Issue by AutisticCoder** [Sorrow446/Qo-DL-Reborn#15]
Hello,
I encountered this bug when trying to use the cli
`:\Users\z5205847\Downloads\Qo-DL-Reborn-master\Qo-DL-Reborn-master>python qo-dl_reborn.py
Traceback (most recent call last):
  File "qo-dl_reborn.py", line 21, in <module>
    client = qopy.Client()
  File "C:\Users\z5205847\Downloads\Qo-DL-Reborn-master\Qo-DL-Reborn-master\qopy\qopy.py", line 16, in __init__
    self.id, self.sec = self.cfg_setup(False)
  File "C:\Users\z5205847\Downloads\Qo-DL-Reborn-master\Qo-DL-Reborn-master\qopy\qopy.py", line 165, in cfg_setup
    if self.test_secret(id, secret):
  File "C:\Users\z5205847\Downloads\Qo-DL-Reborn-master\Qo-DL-Reborn-master\qopy\qopy.py", line 151, in test_secret
    r = self.api_call('userLibrary/getAlbumsList?', id=id, sec=sec)
  File "C:\Users\z5205847\Downloads\Qo-DL-Reborn-master\Qo-DL-Reborn-master\qopy\qopy.py", line 65, in api_call
    "user_auth_token": self.uat,
AttributeError: 'Client' object has no attribute 'uat'`

**Comment by Sorrow446** [comment]
Fixed. https://github.com/Sorrow446/Qo-DL-Reborn/releases/tag/R1a
